// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTj1tWHU0I6OcbWqwmZY336ERkmYwU3Dg',
    appId: '1:1027438480518:web:337c230faeda4eb5d11507',
    messagingSenderId: '1027438480518',
    projectId: 'ecommerce-90718',
    authDomain: 'ecommerce-90718.firebaseapp.com',
    storageBucket: 'ecommerce-90718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZYSAdv5jbrsLyzweVniyS6E4DNszMyU',
    appId: '1:1027438480518:android:08f6573b2b51f554d11507',
    messagingSenderId: '1027438480518',
    projectId: 'ecommerce-90718',
    storageBucket: 'ecommerce-90718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQnZro4RVtPvJpmgBIbeFGQXvrpLFx6I',
    appId: '1:1027438480518:ios:99e463ab01db5095d11507',
    messagingSenderId: '1027438480518',
    projectId: 'ecommerce-90718',
    storageBucket: 'ecommerce-90718.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQnZro4RVtPvJpmgBIbeFGQXvrpLFx6I',
    appId: '1:1027438480518:ios:99e463ab01db5095d11507',
    messagingSenderId: '1027438480518',
    projectId: 'ecommerce-90718',
    storageBucket: 'ecommerce-90718.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTj1tWHU0I6OcbWqwmZY336ERkmYwU3Dg',
    appId: '1:1027438480518:web:65b4a7c4c4bc464dd11507',
    messagingSenderId: '1027438480518',
    projectId: 'ecommerce-90718',
    authDomain: 'ecommerce-90718.firebaseapp.com',
    storageBucket: 'ecommerce-90718.appspot.com',
  );
}